sequenceDiagram
    participant F as Frontend
    participant B as Backend
    participant D as Database
    Note over F, D: user (uid), business(bid), stars(ratings), photos (pid)
    B->>D: Query uid, bid, stars from Reviews Table
    D->>B: Queried Reviews data
    B->>B: Train & Predict
    B->>F: List of available users (uid)
    F->>F: Randomly chose user (uid)
    F->>B: Request user information
    B->>D: Query user data from Users Table
    D->>B: Queried user data
    B->>F: User information
    F->>B: Recommendations request for user
    B->>F: List of recommendations (bid's)
    F->>B: Request business information
    B->>D: Query business data from Business Table
    D->>B: Queried business data
    B->>F: Business Information
    F->>B: Request business's review content
    B->>D: Query content from Reviews Table
    D->>B: Queried content
    B->>F: Requested business review
    F->>B: Request business's photo id
    B->>D: Query pid from Photos Table
    D->>B: Queried pid
    B->>F: Requested business's photo id
    F->>B: Request photo by pid
    B->>F: Requested photo

